### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by JordanSussman**
# changes

I've added a fairly basic Dockerfile that is based on `python:alpine3.6`

# usage

1. `docker build .`
1. `docker run <image> <notifiers command args>`

Ideally the image would be uploaded to docker hub via a [automated build](https://docs.docker.com/docker-hub/builds/), but travis ci would also work.

I don't see the workflow to publish notifiers to pypi, so if it makes more sense to build from source I'm happy to update the PR with:

```Dockerfile
FROM python:alpine3.6

ADD . /notifiers
WORKDIR /notifiers

RUN pip install --upgrade pip setuptools
RUN pip install -e .
RUN pip install -r requirements.txt

ENTRYPOINT ["notifiers"]
``` 

Thanks!
Jordan

### CODE REVIEW

**Comment by liiight** [comment]
Thanks for this! I have a docker hub account although my usage of docker is so minimal it didn't even occur to me to release there as well.
Could you point me in the right direction on how to correctly do that? 

Also, the tests are failing since prs cannot access secure env vars which are used for the online tests. I thoguht I figured out that issue but obviously it doesn't work. I may use you as a test subject to test the workaround since I can't do it myself.

**Comment by liiight** [comment]
ok, looked into it. Please push the changes you mentioned in the comment to build from source and ill setup the automated builds.

Also i added some debugging to the logs to try and figure out what i did wrong with skipping these online tests from prs

**Comment by JordanSussman** [comment]
Thanks for the quick response. I've updated the `Dockerfile` to build from source. 

Happy to help test the Travis changes.

**Comment by liiight** [comment]
i pushed a fix to the test issue, please sync

**Comment by JordanSussman** [comment]
@liiight the travis tests look good. I'm not really sure why codecov is complaining about lower coverage though.

**Comment by liiight** [comment]
codecov complains because now a lot of the test are skipped which appears to drop the coverage, don't worry about it.

Also, I squashed on merge so no need for any more action on you end. Thanks for this! I'll update here as well when i setup the automated docker build,

**Comment by liiight** [comment]
done: https://hub.docker.com/r/liiight/notifiers/

i'm pushing 0.6.2 so it'll populate master branch

**Comment by JordanSussman** [comment]
Thanks!

fyi - Looks like the auto formatted readme on https://hub.docker.com/r/liiight/notifiers/ isn't rendering the badges. I'm not very familiar with RST, but the following Markdown will work correctly on Dockerhub.

```
[![Travis CI](https://img.shields.io/travis/liiight/notifiers/master.svg?style=flat-square)](https://travis-ci.org/liiight/notifiers)

[![Codecov](https://img.shields.io/codecov/c/github/liiight/notifiers/master.svg?style=flat-square)](https://travis-ci.org/liiight/notifiers)

[![Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg?style=flat-square)](https://gitter.im/notifiers/notifiers)

[![PyPi version](https://img.shields.io/pypi/v/notifiers.svg?style=flat-square)](https://pypi.python.org/pypi/notifiers)

[![Supported Python versions](https://img.shields.io/pypi/pyversions/notifiers.svg?style=flat-square)](https://pypi.org/project/notifiers)

[![License](https://img.shields.io/pypi/l/notifiers.svg?style=flat-square)](https://choosealicense.com/licenses)

[![Status](https://img.shields.io/pypi/status/notifiers.svg?style=flat-square)](https://pypi.python.org/pypi/notifiers)

[![Docker build](https://img.shields.io/docker/build/liiight/notifiers.svg?style=flat-square)](https://hub.docker.com/r/liiight/notifiers/)
```

**Comment by liiight** [comment]
The problem with that is that pypi requires rst...
I'll probably end up having both, generating one on the fly from the other

**Comment by JordanSussman** [comment]
Based on https://github.com/docker/hub-feedback/issues/621 it looks like Docker isn't in any hurry to add rst support 😞. If you wanted to get it fixed in the short term you could manually modify the full description on https://hub.docker.com/r/liiight/notifiers/. However, it isn't a big deal, so eventually having a markdown readme would be great.

**Pull request merged**
